[package]
name = "TimeCapsule"
version = "1.0.0"
authors = ["Your Name"]

[addresses]
time_capsule_addr = "_"

[dev-addresses]
time_capsule_addr = "0x1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"
